### ISSUE TITLE
Error on make init: double requirement of tifffile in requirements.txt

### ISSUE THREAD

**Issue by williamstoy** [AllenInstitute/deepinterpolation#1]
When I run 'make init', I get the following error:

`ERROR: Double requirement given: tifffile==2019.7.26 (from -r requirements.txt (line 64)) (already in tifffile (from -r requirements.txt (line 1)), name='tifffile')`

I am on macOS Catalina 10.15.5

I removed the first line, 'tifffile', and the issue was apparently resolved

**Comment by jeromelecoq** [comment]
Thanks! I will push a new requirement file, today probably.

**Comment by jeromelecoq** [comment]
Fixed. I updated all installation files and dependencies
