### ISSUE TITLE
Imports failing in ophys example notebook in Google colab

### ISSUE THREAD

**Issue by diegoasua** [AllenInstitute/deepinterpolation#13]
Hi,

Thanks for making this package open!

I am having trouble to run the example notebook for multiphoton data in Google colab. In particular this line fails:

```python
from deepinterpolation.generic import JsonSaver, ClassLoader
```

This is the complete error:

```python
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-09a154eed24d> in <module>()
      3 from shutil import copyfile
      4 import os
----> 5 from deepinterpolation.generic import JsonSaver, ClassLoader
      6 import datetime
      7 from typing import Any, Dict

2 frames
/usr/local/lib/python3.6/dist-packages/deepinterpolation/generic.py in <module>()
     96 
     97 
---> 98 class ClassLoader:
     99     """     
    100     ClassLoader allows to select and create a specific Type and Name object from the available library of objects. It then

/usr/local/lib/python3.6/dist-packages/deepinterpolation/generic.py in ClassLoader()
    104 
    105     from deepinterpolation import network_collection
--> 106     from deepinterpolation import generator_collection
    107     from deepinterpolation import trainor_collection
    108     from deepinterpolation import inferrence_collection

/usr/local/lib/python3.6/dist-packages/deepinterpolation/generator_collection.py in <module>()
      9 import nibabel as nib
     10 from scipy.io import wavfile
---> 11 import s3fs
     12 
     13 class MaxRetryException(Exception):

ModuleNotFoundError: No module named 's3fs'
```

Thanks ahead! Looking forward to try this with our data

**Comment by jeromelecoq** [comment]
Hi, 
Not sure why this package did not get installed. It is currently in our requirement 
https://github.com/AllenInstitute/deepinterpolation/blob/master/requirements.txt

s3fs is useful when using file stored on aws s3 buckets. 

you could probably fix this by using "pip install s3fs" within your environment.

How did you install the deepinterpolation package?

**Comment by diegoasua** [comment]
Thanks for the reply!

deepinterpolation was installed via:

```python
! pip install git+https://github.com/AllenInstitute/deepinterpolation.git
```

You were right, the problem was that I was not installing `requirements.txt`. Adding the following line in the notebook after clonning the repo solves the problem:

```python
! pip install -r deepinterpolation/requirements.txt
```

Thanks!

**Comment by jeromelecoq** [comment]
Is it ok to close this issue then? Feel free to close the issue if you think it was.
