### ISSUE TITLE
Error on make init: ophysextractor not found

### ISSUE THREAD

**Issue by williamstoy** [AllenInstitute/deepinterpolation#2]
When I run 'make init', I encounter the following error:

`ERROR: Could not find a version that satisfies the requirement ophysextractor==1.0.0 (from -r requirements.txt (line 36)) (from versions: none)
ERROR: No matching distribution found for ophysextractor==1.0.0 (from -r requirements.txt (line 36))`

A google search, anaconda search, and pypi.org search didn't turn up any packages named 'ophysextractor.'
Is this a private package?

**Comment by jeromelecoq** [comment]
Thanks! I remove this dependency already. Working on a better requirement file as well as an ephys training example.

**Comment by jeromelecoq** [comment]
Fixed. I updated all installation files and dependencies
