### ISSUE TITLE
inference: single location for scaling, dtype specification

### ISSUE THREAD

**Issue by djkapner** [AllenInstitute/deepinterpolation#54]
the inference CLI turns off scaling, and rescales the whole movie to uint16. This was done to resolve a few < 0 values in the prediction floating point output.
We think this should really be done not in the API layer, but, in the inference class, where rescaling is already optionally implemented.

Tasks:
- [ ] in the inner class, implement conversion back to uint16
- [ ] in the API layer, remove the duplicate scaling code. Add control parameters for float or int output.

**Comment by jeromelecoq** [comment]
This was done in the latest version
