### ISSUE TITLE
need to update requirements.txt

### ISSUE THREAD

**Issue by danielsf** [AllenInstitute/deepinterpolation#72]
Naively trying to install `requirements.txt` results in

```
(deepinterpolation) [scott.daniel@synapse deepinterpolation]$ pip install -r requirements.txt 
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.2 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0)
ERROR: No matching distribution found for tensorflow==2.2.2
```

I suspect this is something Google has done (not making tensorflow 2.2.2 pip installable any more), but we should do something in response to it.

**Comment by danielsf** [comment]
Just updating tensorflow resulted in
```
ERROR: Could not find a version that satisfies the requirement scipy==1.4.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0rc1, 1.6.0rc2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0rc1, 1.7.0rc2, 1.7.0, 1.7.1, 1.7.2)
ERROR: No matching distribution found for scipy==1.4.1
```

This requirements.txt seems to work
```
tensorflow==2.5.0
nibabel
matplotlib
python-dateutil
scipy==1.6.3
tifffile
s3fs
argschema==2.0.2
mlflow==1.14.1
```

**Comment by jeromelecoq** [comment]
Yes. I agree. I ran some tests last week. See here: https://github.com/AllenInstitute/deepinterpolation/pull/67

I found that 2.5 and 2.6 would break our tests. I recommend 2.4 and 2.7

**Comment by jeromelecoq** [comment]
@danielsf Just something that confused me. 
do you have a sense why our testing engine did not grab this issue? It is installing the package from requirement as far as I understand.

**Comment by danielsf** [comment]
interesting.... the test engine is running python 3.7. It looks like tensorflow 2.2.2 *is* available for python 3.7. I just run python 3.9 without thinking any more, which is why I had problems.

**Comment by jeromelecoq** [comment]
Ah good catch!

**Comment by jeromelecoq** [comment]
But now, does 2.5 actually work with the package in python 2.9? I had pretty serious error message running training and inference?

**Comment by danielsf** [comment]
(I assume you meant python 3.9 and 3.7...)

I didn't run any of your unit tests, but, yes: I installed tensorflow 2.5 in a python 3.9 environment and was able to run inference on our 2P movies.

I have not ever tried to run training. I was just trying to get some new denoised movies to run segmentation on.

**Comment by jeromelecoq** [comment]
See here : https://app.circleci.com/pipelines/github/AllenInstitute/deepinterpolation/356/workflows/45f92137-a6ca-4b09-af46-06e80805a5a1/jobs/775
(I think you should be able to login in cicrcleci?)

test with tensorflow 2.5 + python 2.7
It fails on the mlflow test actually.

**Comment by danielsf** [comment]
One thing I noticed when hacking requirements.txt for my fork was that the requirements were overspecified (inconsistent versions of numpy an scipy were specified, I think).

I wonder what would happen if you specified a version of tensorflow, but did not specify a version of mlflow. `pip` would then be free to grab whatever version of mlflow was consistent with the version of tensorflow you specified, which might resolve the problem (though... the fact that `pip` isn't complaining about version mismatch probably means that tensorflow and/or mlflow haven't kept track of their mutual incompatibilities)

**Comment by jeromelecoq** [comment]
Yes, this scipy came from an older incompatibility. I am still worry of h5py which I found to be sensitive. We might need to add more test coverage if we set these loose.

**Comment by jeromelecoq** [comment]
I would want to make sure tensorflow can load older h5 models with different h5py version for example

**Comment by jeromelecoq** [comment]
I have updated the requirements
